version: '3.8'

volumes:
  tg_bot_postgres_data: {}
  static_data: {}

networks:
  tg_bot_network:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: tg_bot_django_image:latest
    container_name: tg_bot_django_container
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_data:/app/vol
      - ./app/:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - tg_bot_network

  postgres:
    image: postgres:15.5-alpine3.18
    container_name: tg_bot_postgres_container
    restart: unless-stopped
    volumes:
      - tg_bot_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=tg_bot_template
    env_file:
      - ./.env
    networks:
      - tg_bot_network
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -p 5432